### ISSUE TITLE
Version in sub pom.xml files was not updated

### ISSUE THREAD

**Issue by andlinger** [InterNetX/java-domainrobot-sdk#11]
The version in the pom.xml files in the subprojects is 0.2.2. In the root project the version is 0.2.3.

**Comment by Ephenodrom** [comment]
I will take a look into this tomorrow.

**Comment by Ephenodrom** [comment]
@andlinger 

I updated all sub modules to the same main version. Please use the latest release. 

Hint: We plan on setting up a public repository for this sdk and then automate the build and deploy process. But due to holidays starting this week, this will take some more time.
