### ISSUE TITLE
Contact.create always returns error

### ISSUE THREAD

**Issue by andlinger** [InterNetX/java-domainrobot-sdk#12]
No matter which data is specified, the same error is always returned. I have not found a variant where the request was successful. 
Which data must be sent?

`[{"stid":"ID","messages":[{"text":"Fehler bei der internen Verarbeitung.","code":"EF00602","status":"ERROR"}],"status":{"code":"E0301","text":"Domain-Kontakt konnte nicht angelegt werden.","type":"ERROR"}}]`

I have used the fields from this example in a modified way. But it did not work either.
https://help.internetx.com/display/APIXMLDE/Contact+Create

**Comment by Ephenodrom** [comment]
I will take a look into this tomorrow.

**Comment by Ephenodrom** [comment]
Hello @andlinger,

The problem was the parsing of the object to a json string. Every null value was printed out as null and this causes some strange errors on the api side. So I updated the json serialising. Now this works and you receive a proper error from the API. Check out the example below. Please use the latest releas.

```java
        String user = "";
        String password = "";
        String context = "";
        String baseUrl = "";
        Domainrobot sdk = new Domainrobot(user, context, password, baseUrl);

        Contact c = new Contact();
        c.setFname("Jon");
        try {
            sdk.getContact().create(c, null);
        } catch (DomainrobotApiException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        } catch (Exception e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
```
