### ISSUE TITLE
DomainrobotApiException is not used

### ISSUE THREAD

**Issue by andlinger** [InterNetX/java-domainrobot-sdk#13]
With errors from the API a DomainrobotApiException is never thrown but mostly a HttpServerErrorException$InternalServerError.

Shouldn't the exception mentioned above be thrown if an error occurs from the API?

**Comment by Ephenodrom** [comment]
@andlinger Please use the latest release. I updated the error handling. Every API call will throw an DomainrobotApiException or an any other exception. The HttpClientErrorException and HttpServerErrorException are now mapped to a DomainrobotApiException.

```
try {
            sdk.getContact().create(c, null);
        } catch (DomainrobotApiException e) {
            // Some error from the API
            e.printStackTrace();
        } catch (Exception e) {
            // Handle unknown error. Maybe this is a error the from sdk!
            e.printStackTrace();
        }

```
