### ISSUE TITLE
PollMessage.getId is a Long, Domainrobot.poll.confirm takes an Integer

### ISSUE THREAD

**Issue by andlinger** [InterNetX/java-domainrobot-sdk#19]
In the PollMessage object, a value of type Long is returned as ID. However, an integer is required in the method Domainrobot.poll.confirm.

**Comment by Jabanto** [comment]
Hello @andlinger

The method is changed now the confin() use a (long) id value as the model,  
Thanks for feedback .
See the change will be added on the next realese

Best regards

**Comment by Ephenodrom** [comment]
Hello @andlinger 
The new release is ready and this is fixed with version 0.2.7.

Regards
