### ISSUE TITLE
Missing ResourceRecords when creating a zone

### ISSUE THREAD

**Issue by andlinger** [InterNetX/java-domainrobot-sdk#22]
When creating a zone, sometimes resource records are missing. 
The error is easily reproducible. 

When creating a zone we want to create the following two ResourceRecords automatically:

| Name | TTL  | Type | Value   |
|------|------|------|---------|
| www  | 3600 |   A  | 9.9.9.9 |
|      | 3600 | A    | 9.9.9.9 |

But as soon as a ResourceRecord has an entry without the "name" field, only the ResourceRecord without "name" is created. The others, in this case "www", are ignored.

# Example 1

Following ResourceRecords were sent:

| Name | TTL  | Type | Value   |
|------|------|------|---------|
| www  | 3600 |   A  | 172.18.0.3 |
|  [null]  | 3600 | A    | 172.18.0.3 |

The zone object before it was sent:

```java
class Zone {
    created: null
    updated: null
    origin: zoneerror1.de
    idn: null
    soa: class Soa {
        refresh: 43200
        retry: 7200
        expire: 1209600
        ttl: 900
        email: mail@mx.io
    }
    dnssec: null
    nameServerGroup: null
    allowTransfer: null
    owner: null
    updater: null
    logId: null
    comment: null
    domainsafe: null
    source: null
    sourceVirtualHostname: null
    nameServers: [class NameServer {
        name: a.demo.autodns.com
        ttl: null
        ipAddresses: null
    }, class NameServer {
        name: b.demo.autodns.com
        ttl: null
        ipAddresses: null
    }]
    main: null
    wwwInclude: null
    virtualNameServer: null
    freeText: null
    action: null
    grants: null
    resourceRecords: [class ResourceRecord {
        name: www
        ttl: 3600
        type: A
        value: 172.18.0.3
        pref: null
        raw: null
    }, class ResourceRecord {
        name: null
        ttl: 3600
        type: A
        value: 172.18.0.3
        pref: null
        raw: null
    }]
    roid: null
}

```

The following entries were displayed in the AutoDNS panel after calling ZoneClient.create:

![Bildschirmfoto 2020-08-27 um 13 58 54](https://user-images.githubusercontent.com/1436448/91440745-59925e80-e86f-11ea-83a6-181cfa5f2ba3.png)

# Example 2

Following ResourceRecords were sent:

| Name | TTL  | Type | Value   |
|------|------|------|---------|
| www  | 3600 |   A  | 172.18.0.3 |
|    | 3600 | A    | 172.18.0.3 |

The zone object before it was sent:

```java
class Zone {
    created: null
    updated: null
    origin: zoneerror2.de
    idn: null
    soa: class Soa {
        refresh: 43200
        retry: 7200
        expire: 1209600
        ttl: 900
        email: maiil@mx.io
    }
    dnssec: null
    nameServerGroup: null
    allowTransfer: null
    owner: null
    updater: null
    logId: null
    comment: null
    domainsafe: null
    source: null
    sourceVirtualHostname: null
    nameServers: [class NameServer {
        name: a.demo.autodns.com
        ttl: null
        ipAddresses: null
    }, class NameServer {
        name: b.demo.autodns.com
        ttl: null
        ipAddresses: null
    }]
    main: null
    wwwInclude: null
    virtualNameServer: null
    freeText: null
    action: null
    grants: null
    resourceRecords: [class ResourceRecord {
        name: www
        ttl: 3600
        type: A
        value: 172.18.0.3
        pref: null
        raw: null
    }, class ResourceRecord {
        name: 
        ttl: 3600
        type: A
        value: 172.18.0.3
        pref: null
        raw: null
    }]
    roid: null
}

```

The following entries were displayed in the AutoDNS panel after calling ZoneClient.create:

![Bildschirmfoto 2020-08-27 um 13 59 52](https://user-images.githubusercontent.com/1436448/91440868-8f374780-e86f-11ea-87eb-bd37c29ae581.png)

# Example 3

Following ResourceRecords were sent:

| Name | TTL  | Type | Value   |
|------|------|------|---------|
| www  | 3600 |   A  | 172.18.0.3 |
|  test  | 3600 | A    | 172.18.0.3 |

The zone object before it was sent:

```java
class Zone {
    created: null
    updated: null
    origin: zoneerror3.de
    idn: null
    soa: class Soa {
        refresh: 43200
        retry: 7200
        expire: 1209600
        ttl: 900
        email: mail@mx.io
    }
    dnssec: null
    nameServerGroup: null
    allowTransfer: null
    owner: null
    updater: null
    logId: null
    comment: null
    domainsafe: null
    source: null
    sourceVirtualHostname: null
    nameServers: [class NameServer {
        name: a.demo.autodns.com
        ttl: null
        ipAddresses: null
    }, class NameServer {
        name: b.demo.autodns.com
        ttl: null
        ipAddresses: null
    }]
    main: null
    wwwInclude: null
    virtualNameServer: null
    freeText: null
    action: null
    grants: null
    resourceRecords: [class ResourceRecord {
        name: www
        ttl: 3600
        type: A
        value: 172.18.0.3
        pref: null
        raw: null
    }, class ResourceRecord {
        name: test
        ttl: 3600
        type: A
        value: 172.18.0.3
        pref: null
        raw: null
    }]
    roid: null
}
```

The following entries were displayed in the AutoDNS panel after calling ZoneClient.create:

![Bildschirmfoto 2020-08-27 um 14 00 46](https://user-images.githubusercontent.com/1436448/91440934-a9712580-e86f-11ea-827b-4b31d9fa6b96.png)

**Comment by Jabanto** [comment]
Hello @andlinger

 All right we take care of this issue  and  we will inform you when we solve/have more info about it the, thanks for the feedback

Best Regards

**Comment by andlinger** [comment]
I have some more information. If I have two entries without a "name" field, both entries are added. But again not entries with "name" field.

| Name | TTL  | Type | Value   |
|------|------|------|---------|
| www  | 3600 |   A  | 9.9.9.9 |
| www  | 3600 |   AAAA  | 2001:db8:0:1:1:1:1:1 |
|      | 3600 | A    | 9.9.9.9 |
|      | 3600 | AAAA    | 2001:db8:0:1:1:1:1:1 |

When will you be able to fix this?

**Comment by Jabanto** [comment]
Hello @andlinger 

I have search more info about the Issue,  as a resume you need to set the  **wwwInclude** variable, with **FALSE boolean value**.

Here a Code Example if you make these manual using the SDK , with the Example 1 Request that you write.

          ` Zone newTestZone = new Zone();	        
	        newTestZone.setOrigin("zoneerror1.de");
	          
                //Soa Object
	        Soa soaTest = new Soa();
	        soaTest.setRefresh(43200L);
	        soaTest.setRetry(7200L);
	        soaTest.setExpire(1209600L);
	        soaTest.setTtl(900L);
	        soaTest.setEmail("office@netzadresse.at");
	        newTestZone.setSoa(soaTest);
	        //Name Servers
	        List<NameServer> listNS = new ArrayList<NameServer>();
	        NameServer nsTest1 = new NameServer();
	        NameServer nsTest2 = new NameServer();
	        nsTest1.setName("a.demo.autodns.com");
	        nsTest2.setName("b.demo.autodns.com");
	        
	        listNS.add(nsTest1);
	        listNS.add(nsTest2);
	        newTestZone.setNameServers(listNS); 
	        //Resources
	        ResourceRecord resource1 = new ResourceRecord();
	        ResourceRecord resource2 = new ResourceRecord();
	        
            resource1.setName("www");
            resource1.setTtl(3600L);
            resource1.setType("A");
            resource1.setValue("172.18.0.3");
            
            resource2.setTtl(3600L);
            resource2.setType("A");
            resource2.setValue("172.18.0.3");
            
            List<ResourceRecord> recordes = new ArrayList<>();
	        recordes.add(resource1);
	        recordes.add(resource2);
	        
	        newTestZone.setResourceRecords(recordes);
	        newTestZone.setWwwInclude(Boolean.FALSE);


Or here the Json Request,

`
{
    "origin": "zoneerror1.de",
    "soa": {
        "refresh": 43200,
        "retry": 7200,
        "expire": 1209600,
        "ttl": 900,
        "email": "office@netzadresse.at"
    },
    "nameServers": [
        {
            "name": "a.demo.autodns.com"
        },
        {
            "name": "b.demo.autodns.com"
        }
    ],
    "wwwInclude": false,
    "resourceRecords": [
        {
            "name": "www",
            "ttl": 3600,
            "type": "A",
            "value": "172.18.0.3"
        },
        {
            "ttl": 3600,
            "type": "A",
            "value": "172.18.0.3"
        }
    ]
}
`

Explanation:

In fact all your Entries are created , but you dont see these on the AUTODNs panel cuz when you create the Zone you need to set the variable **wwwvalue** to FALSE on your request, cuz if this  is not defined will be use a default value TRUE. and them you cann not see the Entry's (with www) on your Autodns Panel .

Extra Information
Normally You can check that all you entries are the if you create a Zone **on live** (carefully), for example in you use dig www.google.de ANY or dig zone.de ANY on Linux Terminal or using Cmder for Windows., you will able to see all the resourceRecords 

So please Try again the request and we wait for your Feedback, 

Thanks you ! 
 
Best Regards

Hugo Abanto

**Comment by andlinger** [comment]
Super. This fixes the problem
