### ISSUE TITLE
ContactClient.list fails with empty query

### ISSUE THREAD

**Issue by andlinger** [InterNetX/java-domainrobot-sdk#9]
Sending a request via ContactClient.list with a empty query returns with following error:

`E0304001 : Der Domain-Kontakt fehlt. Gib entweder die Domain-Kontakt- ID oder den Namen des Kontaktes an.`

So it's not possible to list all contact handles.

**Comment by Ephenodrom** [comment]
Hello @andlinger 

Thanks for opening the issue, I will investigate and hopefully provide a solution soon.

**Comment by Ephenodrom** [comment]
Hello @andlinger 
This should be fixed now. The problem was that the method used the wrong http method. I changed the GET to POST.

Please use the newest release 0.2.3.
